pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/2200032172/Ecommerce-devops.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Docker Build & Push') {
            steps {
                bat '''
                docker build -t your-dockerhub-username/your-app .
                docker login -u your-dockerhub-username -p your-password
                docker push your-dockerhub-username/your-app
                '''
            }
        }

        stage('Deploy to AWS (Later)') {
            steps {
                echo 'Deploying to AWS...'
            }
        }
    }
}
