version: '3.8'

services:
  frontend:
    build:
      context: ../ecommerce-frontend/project
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/ecommerce_db?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Nishita@2004
    depends_on:
      mysql_db:
        condition: service_healthy
    restart: always

  mysql_db:
    image: mysql:8
    container_name: mysql_db_new
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nishita@2004
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"   # Changed from 3307:3306 to avoid conflicts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql   # Attach volume for persistent database storage

volumes:
  db_data:   # Ensure volume is correctly configured
